In [1]:
import numpy as np

In [117]:
def softmax(z):
    """z is a numpy array of a list(maybe)"""
    exp_z = np.exp(z)
    return exp_z/np.sum(exp_z)

def cross_entropy():
    pass

def d_loss_dt(arr,j_th,class_number):
    #print(arr.shape)
    #print(j_th,class_number)
    #arr = np.array(arr)
    res = 0
    if j_th == class_number :
        res = arr[class_number] - 1 
    else:
        res = arr[j_th]
    return res

In [7]:
x = np.array([1.02,45,-56,-70.4,56],dtype='float32')
softmax(x)

array([1.3258127e-24, 1.6701422e-05, 0.0000000e+00, 0.0000000e+00,
       9.9998331e-01], dtype=float32)

In [11]:
x.shape

(5,)

In [118]:
class SoftmaxCLassifier():
    def __init__(self,num_classes,num_epochs=1,num_iter=1000,lr=0.001):
        self.weight = None
        self.bias = None
        self.num_classes = num_classes
        self.lr = lr
        self.num_epochs = num_epochs
        self.num_feature = None
        self.num_samples = None
        self.num_iter = num_iter

    def parametrize(self,X):
        self.num_samples,self.num_feature = X.shape
        self.weight = np.random.rand(self.num_classes,self.num_feature)
        self.bias = np.random.rand(self.num_classes)

    def train(self,X,y):        
        for epoch in range(self.num_epochs): 
            for _ in range(self.num_iter): 
                for j in range(self.num_samples):
                    pred = np.dot(self.weight,X[j]) + self.bias
                    pred_hat = softmax(pred)
                
                    for k in range(self.num_classes):
                        self.weight[k] -= self.lr * d_loss_dt(pred_hat,k,y[j]) * X[j]
                        self.bias[k] -= self.lr * d_loss_dt(pred_hat,k,y[j])

    def predict(self,X):
        lin = np.dot(self.weight,X) + self.bias
        soft = softmax(lin)
        return np.argmax(soft)

In [147]:
X = np.array([[1,0,0],[2,0,0],[0,5,0],[0,1,0],[0,0,1],[0,0,2],[0,0,89],[0,2,0]],dtype='float32')
y = np.array([0,0,1,1,2,2,2,1])

In [148]:
clf = SoftmaxCLassifier(3)

In [149]:
clf.parametrize(X)

In [150]:
clf.train(X,y)

In [155]:
m = np.array([0,20,0])
clf.predict(m)

np.int64(1)

In [152]:
print(clf.weight)

[[ 1.28347039 -0.24854933 -0.04878021]
 [-0.0449028   1.48193405 -0.09819433]
 [-0.22217131  0.11230584  1.74573419]]


In [153]:
print(clf.bias)

[0.4415352  0.36371202 0.09068946]
